# Default target executed when no arguments are given to make
all: help

recommend:
	python demos/recommend.py

scrape_scholarly:
	python demos/scrape_scholarly.py

help:
	@echo '===================='
	@echo '-- SCRIPTS --'
	@echo 'recommend - runs recommendation demo'
	@echo 'scrape_scholarly - runs scholarly scrapper'
	@echo '-- DOCUMENTATION tasks are from the top-level Makefile --'